#!/bin/bash
# Bài 6 - Quick Setup Guide

echo "=== Bài 6: Thymeleaf Layout Demo ==="
echo ""
echo "✅ Project structure:"
echo "  - 4 Java files (Main, WebConfig, EmployeeController, Employee)"
echo "  - 4 HTML templates (_layout, list-employees, add-employee, result)"
echo "  - 2 Config files (pom.xml, web.xml)"
echo ""
echo "🚀 To run:"
echo "  1. Open IntelliJ IDEA"
echo "  2. Open folder: baitap2/baitap6"
echo "  3. Find Main.java in src/main/java/com/example/"
echo "  4. Right-click → Run 'Main.main()'"
echo "  5. Open browser: http://localhost:8080/employees/list"
echo ""
echo "📋 Endpoints:"
echo "  - GET  /employees/list   → Employee list"
echo "  - GET  /add-employee     → Add form"
echo "  - POST /submit-employee  → Form submission"
echo ""
echo "✨ Features:"
echo "  - Thymeleaf layout inheritance"
echo "  - Form binding (th:object, th:field)"
echo "  - List iteration (th:each)"
echo "  - Conditional styling (th:if)"
echo "  - Switch/case (th:switch)"
echo ""
echo "Done! ✅"

